# Generated by Django 3.1.4 on 2021-03-04 07:59

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20210304_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='slug',
            field=autoslug.fields.AutoSlugField(allow_unicode=True, default='dwad', editable=False, populate_from='title'),
            preserve_default=False,
        ),
    ]
